apiVersion: v1
kind: Pod
metadata:
  name: poddemo
  labels:
    env: production
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
  - name: dockerone
    image: vijayshinva/dockerone
    volumeMounts:
      - mountPath: /usr/share/vijay/html
        name: html
        readOnly: true
    resources:
        requests:
          memory: 64Mi
          cpu: 250m
          ephemeral-storage: 250Mi
        limits:
          memory: 128Mi
          cpu: 500m
    livenessProbe:
        httpGet:
            path: /liveness/probe
            port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1