apiVersion: v1
kind: Service
metadata:
  name: dockerone-service-np
spec:
  type: NodePort
  selector:
    app: dockerone
  ports:
    - protocol: TCP
      nodePort: 32323 # External Port
      port: 8080 # Internal Port
      targetPort: 80