apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dockerone-deployment-scaler
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dockerone-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization