apiVersion: v1
kind: ResourceQuota
metadata:
  name: dockerone-resources
spec:
  hard:
    requests.cpu: 250m
    requests.memory: 100Mib
    limits.cpu: 1000m
    limits.memory: 500Mib
    configmaps: "10" 
    persistentvolumeclaims: "4" 
    replicationcontrollers: "20" 
    secrets: "10" 
    services: "10"