apiVersion: v1
kind: Pod
metadata:
  name: poddemo
  labels:
    env: production
spec:
  containers:
  - name: dockerone
    image: vijayshinva/dockerone
    resources:
        requests:
          memory: 64Mi
          cpu: 250m  # One cpu, in Kubernetes, is equivalent to 1 Azure vCore. m => millicpu
          ephemeral-storage: 250Mi
        limits:
          memory: 128Mi
          cpu: 500m
    livenessProbe:
        httpGet:
            path: /liveness/probe
            port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1
  nodeSelector:
    customlabel: vijay